<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Scripts\config\webpack.config.js" />
    <Content Include="Scripts\src\Index.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JavaScriptEngineSwitcher.Extensions.MsDependencyInjection" Version="3.3.0" />
    <PackageReference Include="JavaScriptEngineSwitcher.V8" Version="3.14.0" />
    <PackageReference Include="JavaScriptEngineSwitcher.V8.Native.win-x64" Version="3.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.8" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="React.AspNet" Version="5.2.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AAServer.Application\AAServer.Application.csproj" />
    <ProjectReference Include="..\AAServer.Service\AAServer.Service.csproj" />
  </ItemGroup>



</Project>
